name: Flutter Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'  # Set Java version as required for your project

      - name: Install Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.0.5'  # Specify the Flutter version you need

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: tools platform-tools system-images;android-30;default;x86_64 platforms;android-30 emulator
          
      - name: Set up Android emulator
        run: |
          avdmanager create avd -n JP -k "system-images;android-30;default;x86_64" --force --device "pixel"

      - name: Search for .ini
        run: find . -name "JP.ini"
          
      - name: List AVDs
        run:
          ls /usr/local/lib/.android/avd

      - name: Start Emulator
        run:
          /usr/local/lib/android/sdk/emulator/./emulator -avd JP -no-audio -no-window &

      - name: Run Flutter tests
        run: flutter test integration_test/app_test.dart

