name: Android Emulator CI

on: [push, pull_request]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java Environment
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        unzip commandlinetools-linux-11076708_latest.zip -d $HOME/Android/Sdk/cmdline-tools
        rm commandlinetools-linux-11076708_latest.zip
        yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --install "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86"

    - name: Create and start Android Emulator
      run: |
        echo "no" | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --licenses
        $HOME/Android/Sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --force
        nohup $HOME/Android/Sdk/emulator/emulator -avd test -no-window -no-audio -gpu swiftshader_indirect &

    - name: Wait for Emulator to start
      run: |
        timeout 90 bash -c 'until echo "adb devices" | adb shell; do sleep 5; done'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.14.0
      with:
        flutter-version: 3.0.5
        channel: stable

    - name: Flutter doctor
      run: flutter doctor --verbose

    - name: Flutter clean
      run: flutter clean

    - name: Flutter pub get
      run: flutter pub get

    - name: Run tests
      run: flutter test integration_test/app_test.dart


