name: Flutter Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'  # Set Java version as required for your project

      - name: Install Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.0.5'  # Specify the Flutter version you need

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Patrol
        run: |
          dart pub global activate patrol_cli
          export PATH=$PATH:$HOME/.pub-cache/bin

      - name: Patrol Doctor
        run: patrol doctor


      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          api-level: 35
          arch: x86_64
          profile: 'pixel_6_pro'
          script: flutter test integration_test/app_test.dart
