name: Flutter Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'  # Set Java version as required for your project

      - name: Install Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.0.5'  # Specify the Flutter version you need

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          api-level: 30
          arch: x86_64
          profile: 'Nexus 6'
          script: adb devices

      - name: Connect to created emulator
        run: |
          emulator -port 5554 -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -accel off &
          adb -s emulator-5554 shell getprop sys.boot_completed
          adb -s emulator-5554 shell settings put global window_animation_scale 0.0
          adb -s emulator-5554 shell settings put global transition_animation_scale 0.0
          adb -s emulator-5554 shell settings put global animator_duration_scale 0.0
          adb connect emulator-5554

      - name: Run Flutter tests
        run: flutter test integration_test/app_test.dart

