name: Flutter Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '17'  # Set Java version as required for your project

      - name: Install Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.0.5'  # Specify the Flutter version you need

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Install and configure Patrol
        run: |
          dart pub global activate patrol_cli
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Patrol Doctor
        run: patrol doctor

      - name: Start Android Emulator
        run: |
          sudo mkdir -p /opt/android-sdk/emulator && \
          sudo chmod 777 /opt/android-sdk/emulator && \
          echo 'no' | sudo sdkmanager --install "system-images;android-35;google_apis;x86_64"
          $ANDROID_SDK_ROOT/emulator/emulator -avd pixel_6_pro -no-window -no-audio -gpu swiftshader_indirect &

      - name: Wait for Emulator to boot
        run: |
          timeout 120 sh -c 'until adb shell getprop sys.boot_completed | tr -d '\r' | grep -m1 "1"; do sleep 5; done'

      - name: Run Integration Tests
        run: flutter test integration_test/app_test.dart
