name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0

      - name: Flutter doctor output
        run: flutter doctor --verbose

      - name: Flutter pub get
        run: flutter pub get

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          arch: arm64-v8a
          api-level: 33
          cores: 4
          ram-size: 4000M
          avd-name: Tests
          disable-linux-hw-accel: false
          script: ./gradlew connectedCheck
          
      - name: Run Tests
        run: flutter test integration_test/app_test.dart
