name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Android Emulator
        uses: vgaidarji/android-github-actions-emulator@v1.0.1

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test integration_test
