name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz
          tar xf flutter_linux_3.24.3-stable.tar.xz
          echo 'export PATH="$PATH:$HOME/flutter/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Upgrade Flutter to latest version
        run: flutter upgrade

      - name: Flutter doctor output
        run: flutter doctor --verbose
          
      - name: Download Emulator System Images
        run: sdkmanager --update && sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create and Start Emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d pixel
          emulator -avd test -no-window -no-audio &

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test integration_test
