name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: flutter-android-sdk
        uses: andreujuanc/flutter-android-sdk@v1.0.6

      - name: Upgrade Flutter to latest version
        run: flutter upgrade

      - name: Flutter doctor output
        run: flutter doctor --verbose
          
      - name: Download Emulator System Images
        run: sdkmanager --update && sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create and Start Emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d pixel
          emulator -avd test -no-window -no-audio &

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test integration_test
