name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0

      - name: Flutter doctor output
        run: flutter doctor --verbose

      - name: Flutter pub get
        run: flutter pub get

      - name: Android Emulator Runner
        uses: vgaidarji/android-github-actions-emulator@v1.0.1

      - name: Run Tests
        run: flutter test integration_test/app_test.dart
