name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          api-level: 30  # Specify the desired API level
          target: google_apis
          arch: x86_64

      - name: Download Emulator System Images
        run: sdkmanager --update && sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create and Start Emulator
        run: |
          echo no | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d pixel
          emulator -avd test -no-window -no-audio &

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test integration_test
