name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0

      - name: Flutter doctor output
        run: flutter doctor --verbose

      - name: Flutter pub get
        run: flutter pub get

      - name: Setup Java - Gradle
        uses: yumemi-inc/setup-java-gradle@v1.0.0


      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          arch: x86_64
          api-level: 33
          cores: 4
          ram-size: 4000M
          avd-name: Tests
          disable-linux-hw-accel: true
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            ./gradlew connectedAndroidTest --continue
          
      - name: Run Tests
        run: flutter test integration_test/app_test.dart
